In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.25, random_state=42)

In [7]:
svm = SVC(gamma='scale')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9866666666666667

In [9]:
#lrm = LogisticRegression(solver='liblinear', multi_class='ovr')
lrm = LogisticRegression(solver='liblinear')
lrm.fit(X_train, y_train)
lrm.score(X_test, y_test)

0.9666666666666667

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.98

In [13]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=2)
kf

KFold(n_splits=2, random_state=None, shuffle=False)

In [15]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[5 6 7 8] [0 1 2 3 4]
[0 1 2 3 4] [5 6 7 8]


In [17]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [19]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver="liblinear"), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='scale'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=20), X_train, X_test, y_train, y_test))
    

In [21]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [23]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [25]:
scores_rf

[0.9215358931552587, 0.9315525876460768, 0.9098497495826378]

In [27]:
from sklearn.model_selection import cross_val_score

In [31]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [55]:
cross_val_score(SVC(gamma='auto', kernel='linear'), digits.data, digits.target, cv=3)

array([0.93489149, 0.95826377, 0.93823038])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93322204, 0.94657763, 0.92153589])

In [67]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores1)

0.946576660459342

In [73]:
scores2=cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target, cv=10)
np.average(scores1)

0.946576660459342